# Generated by Django 5.1.7 on 2025-05-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Entregado',
            field=models.BooleanField(default=False),
        ),
    ]
